name: nli_lstm
program: run_wandb_lstm_nli.py
method: bayes
metric:
  name: best_validation_accuracy
  goal: maximize
parameters:
  # hyperparameters start with overrides
  # Ranges
  overrides.model.input_size:
    min: 100
    max: 500
    distribution: q_uniform
  overrides.model.hidden_size:
    min: 100
    max: 500
    distribution: q_uniform
  overrides.model.projection_size:
    min: 50
    max: 1000
    distribution: q_uniform
  overrides.model.num_layers:
    values: [1,2,3]
  overrides.model.bidirectional:
    #values: ["true", "false"]
    value: "true"
  overrides.trainer.optimizer.lr:
    min: -7.0
    max: 0
    distribution: log_uniform
  overrides.trainer.optimizer.weight_decay:
    min: -12.0
    max: -5.0
    distribution: log_uniform
  overrides.model.type:
    value: nli-lstm
  local_config_file:
    value: "configs/lstm_nli.jsonnet"
  subcommand:
    value: train
